language: python

python:
  - "2.7"
  - "3.2"
  - "pypy"

install: "pip install --use-mirrors -r dev_requirements.txt"

script: "python setup.py test"

notifications:
  email:
    - "cmccoy@fhcrc.org"
